In [1]:
!pip install datagouv-client

Collecting datagouv-client

  Downloading datagouv_client-0.5.0-py3-none-any.whl.metadata (14 kB)

Collecting niquests<4,>=3.19.0 (from datagouv-client)
  Downloading niquests-3.21.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tenacity<10,>=9.0.0 in /opt/python/lib/python3.13/site-packages (from datagouv-client) (9.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/python/lib/python3.13/site-packages (from niquests<4,>=3.19.0->datagouv-client) (3.5.1)

Collecting urllib3-future<3,>=2.13.903 (from niquests<4,>=3.19.0->datagouv-client)
  Downloading urllib3_future-2.24.901-py3-none-any.whl.metadata (20 kB)

Collecting wassima<3,>=1.0.1 (from niquests<4,>=3.19.0->datagouv-client)
  Downloading wassima-2.1.3-py3-none-any.whl.metadata (5.6 kB)

Requirement already satisfied: h11<1.0.0,>=0.11.0 in /opt/python/lib/python3.13/site-packages (from urllib3-future<3,>=2.13.903->niquests<4,>=3.19.0->datagouv-client) (0.16.0)

Collecting jh2<6.0.0,>=5.0.3 (from urllib3-future<3,>=2.13.903->niquests<4,>=3.19.0->datagouv-client)
  Downloading jh2-5.0.13-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)

Collecting qh3<2.0.0,>=1.5.4 (from urllib3-future<3,>=2.13.903->niquests<4,>=3.19.0->datagouv-client)
  Downloading qh3-1.9.4-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.1 kB)

Downloading datagouv_client-0.5.0-py3-none-any.whl (21 kB)
Downloading niquests-3.21.0-py3-none-any.whl (230 kB)
Downloading urllib3_future-2.24.901-py3-none-any.whl (811 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.6/811.6 kB 69.6 MB/s  0:00:00
Downloading jh2-5.0.13-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (395 kB)
Downloading qh3-1.9.4-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.4 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 84.6 MB/s  0:00:00
Downloading wassima-2.1.3-py3-none-any.whl (131 kB)

Installing collected packages: wassima, qh3, jh2, urllib3-future, niquests, datagouv-client

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/6 [jh2]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 [urllib3-future]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 [urllib3-future]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 [urllib3-future]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 4/6 [niquests]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [datagouv-client]
Successfully installed datagouv-client-0.5.0 jh2-5.0.13 niquests-3.21.0 qh3-1.9.4 urllib3-future-2.24.901 wassima-2.1.3

In [2]:
from datagouv import Client

In [3]:
import pandas as pd

import requests
import pandas as pd
import time

DATAGOUV_API = "https://www.data.gouv.fr/api/1"

In [4]:
session = requests.Session()
resp = session.get(
            f"{DATAGOUV_API}/datasets/",
            params={"page_size": 10, "page": 1},
            timeout=60,
        )
resp.raise_for_status()
data = resp.json()
items = data.get("data", [])

In [5]:
r=(items[0].get("resources") or [])

In [6]:
";".join([f"{i+1}. {d['title']} - {d['description']}" for i, d in enumerate(r or [])])

''

In [7]:
# items[0]

In [9]:
import requests
import pandas as pd
import time

DATAGOUV_API = "https://www.data.gouv.fr/api/1"

def fetch_datasets_df(page_size=1000, max_pages=None, sleep=0.3) -> pd.DataFrame:
    records = []
    page = 1
    session = requests.Session()

    while True:
        resp = session.get(
            f"{DATAGOUV_API}/datasets/",
            params={"page_size": page_size, "page": page},
            timeout=60,
        )
        resp.raise_for_status()
        data = resp.json()
        items = data.get("data", [])
        if not items:
            break

        for ds in items:
            records.append({
                "id": ds["id"],
                "title": ds.get("title", ""),
                "description": (ds.get("description") or "")[:1000],
                "org": (ds.get("organization") or {}).get("name", ""),
                "org_id": (ds.get("organization") or {}).get("id", ""),
                "tags": ds.get("tags") or [],
                "views": (ds.get("metrics") or {}).get("views", 0),
                "ressources_nb": len(ds.get("resources") or []),
                "ressources_texte": ";".join([f"{i+1}. {d['title']} - {d['description']}" for i, d in enumerate(ds.get("resources") or [])]),
                "downloads": (ds.get("metrics") or {}).get("resources_downloads", 0),
                "license": ds.get("license"),
                "frequency": ds.get("frequency"),
                "last_modified": ds.get("last_modified"),
            })

        print(f"Page {page}: +{len(items)} ({len(records)} total)")
        if not data.get("next_page") or (max_pages and page >= max_pages):
            break
        page += 1
        time.sleep(sleep)

    return pd.DataFrame(records)

In [10]:
df = fetch_datasets_df()

Page 1: +1000 (1000 total)

Page 2: +1000 (2000 total)

Page 3: +1000 (3000 total)

Page 4: +1000 (4000 total)

Page 5: +1000 (5000 total)

Page 6: +1000 (6000 total)

Page 7: +1000 (7000 total)

Page 8: +1000 (8000 total)

Page 9: +1000 (9000 total)

Page 10: +1000 (10000 total)

Page 11: +1000 (11000 total)

Page 12: +1000 (12000 total)

Page 13: +1000 (13000 total)

Page 14: +1000 (14000 total)

Page 15: +1000 (15000 total)

Page 16: +1000 (16000 total)

Page 17: +1000 (17000 total)

Page 18: +1000 (18000 total)

Page 19: +1000 (19000 total)

Page 20: +1000 (20000 total)

Page 21: +1000 (21000 total)

Page 22: +1000 (22000 total)

Page 23: +1000 (23000 total)

Page 24: +1000 (24000 total)

Page 25: +1000 (25000 total)

Page 26: +1000 (26000 total)

Page 27: +1000 (27000 total)

Page 28: +1000 (28000 total)

Page 29: +1000 (29000 total)

Page 30: +1000 (30000 total)

Page 31: +1000 (31000 total)

Page 32: +1000 (32000 total)

Page 33: +1000 (33000 total)

Page 34: +1000 (34000 total)

Page 35: +1000 (35000 total)

Page 36: +1000 (36000 total)

Page 37: +1000 (37000 total)

Page 38: +1000 (38000 total)

Page 39: +1000 (39000 total)

Page 40: +1000 (40000 total)

Page 41: +1000 (41000 total)

Page 42: +1000 (42000 total)

Page 43: +1000 (43000 total)

Page 44: +1000 (44000 total)

Page 45: +1000 (45000 total)

Page 46: +1000 (46000 total)

Page 47: +1000 (47000 total)

Page 48: +1000 (48000 total)

Page 49: +1000 (49000 total)

Page 50: +1000 (50000 total)

Page 51: +1000 (51000 total)

Page 52: +1000 (52000 total)

Page 53: +1000 (53000 total)

Page 54: +1000 (54000 total)

Page 55: +1000 (55000 total)

Page 56: +1000 (56000 total)

Page 57: +1000 (57000 total)

Page 58: +1000 (58000 total)

Page 59: +1000 (59000 total)

Page 60: +1000 (60000 total)

Page 61: +1000 (61000 total)

Page 62: +1000 (62000 total)

Page 63: +1000 (63000 total)

Page 64: +1000 (64000 total)

Page 65: +1000 (65000 total)

Page 66: +1000 (66000 total)

Page 67: +1000 (67000 total)

Page 68: +1000 (68000 total)

Page 69: +1000 (69000 total)

Page 70: +1000 (70000 total)

Page 71: +1000 (71000 total)

Page 72: +1000 (72000 total)

Page 73: +1000 (73000 total)

Page 74: +921 (73921 total)

In [11]:
# environ 8 minutes
df.head()

,id,title,description,org,org_id,tags,views,ressources_nb,ressources_texte,downloads,license,frequency,last_modified
0,6a83d752b69cdec7adb5b08b,Pentest-badges-1787025233,temporary test dataset (to delete),,,[],0,0,,0.0,notspecified,unknown,2026-08-18T03:53:54.091000+00:00
1,6a83d751de1eb0cc2dc96ccc,Pentest-featured-1787025232,temporary test dataset (to delete),,,[],0,0,,0.0,notspecified,unknown,2026-08-18T03:53:53.228000+00:00
2,6a83be503c85cc3fdca9e022,Assemblage de toutes les descriptions des plan...,N_DOCUMENT_PPRN_S_019.shp\n\nAssemblage de tou...,Direction Départementale des Territoires de la...,558bc11cc751df5bfda453ba,"[donnees-ouvertes, inspire, risque-zonages-ris...",0,6,1. Téléchargement simple (Atom) du jeu et des ...,0.0,lov2,unknown,2021-02-01T00:00:00+00:00
3,6a83a5e343be673301a9e031,Vue des servitudes SUP2 des canalisations de t...,Servitudes d’utilité publique liées aux canali...,DREAL Auvergne-Rhône-Alpes,5882a05d88ee3835c59b81a4,"[auvergne-rhone-alpes, canalisations-tmd, drea...",0,2,1. Accès au téléchargement des données - ;2. A...,0.0,notspecified,severalTimesADay,2026-08-18T00:22:59.042000+00:00
4,6a83a58743be673301a9e030,Vue des servitudes SUP3 des canalisations de t...,Servitudes d’utilité publique liées aux canali...,DREAL Auvergne-Rhône-Alpes,5882a05d88ee3835c59b81a4,"[auvergne-rhone-alpes, canalisations-tmd, drea...",0,2,1. Accès au téléchargement des données - ;2. A...,0.0,notspecified,severalTimesADay,2026-08-18T00:21:27.912000+00:00

In [50]:
df.to_parquet("datagouvds.parquet")

In [12]:
!pip install sentence-transformers pyyaml

import yaml
import numpy as np
from sentence_transformers import SentenceTransformer, util

Collecting sentence-transformers

  Downloading sentence_transformers-5.7.0-py3-none-any.whl.metadata (18 kB)

Requirement already satisfied: pyyaml in /opt/python/lib/python3.13/site-packages (6.0.3)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)

  Downloading transformers-5.15.0-py3-none-any.whl.metadata (32 kB)

Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.23.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)

Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Downloading huggingface_hub-1.27.0-py3-none-any.whl.metadata (16 kB)

Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.13.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (38 kB)

Requirement already satisfied: numpy>=1.20.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (2.5.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (4.70.0)
Requirement already satisfied: packaging>=20.0 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.3)
Requirement already satisfied: regex>=2025.10.22 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.7.19)
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading typer-0.27.1-py3-none-any.whl.metadata (16 kB)

Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)

Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Collecting filelock>=3.10.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading filelock-3.32.3-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.7.0)

Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /opt/python/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)

Requirement already satisfied: joblib>=1.4.0 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (84.0.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers)

  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)

Collecting cuda-bindings<14,>=13.0.3 (from torch>=1.11.0->sentence-transformers)
  Downloading cuda_bindings-13.3.1-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch>=1.11.0->sentence-transformers)

  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch>=1.11.0->sentence-transformers)

  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.7.1 (from torch>=1.11.0->sentence-transformers)
  Downloading triton-3.7.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)

Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)

Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)

Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)

Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)

Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence-transformers)
  Downloading cuda_pathfinder-1.6.1-py3-none-any.whl.metadata (1.9 kB)

Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/python/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Collecting shellingham>=1.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)

Requirement already satisfied: annotated-doc>=0.0.2 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/python/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/python/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/python/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-5.7.0-py3-none-any.whl (611 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.3/611.3 kB 47.1 MB/s  0:00:00
Downloading transformers-5.15.0-py3-none-any.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/11.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 82.7 MB/s  0:00:00
Downloading huggingface_hub-1.27.0-py3-none-any.whl (784 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 784.9/784.9 kB 66.1 MB/s  0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.5 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 39.3 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/3.3 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 69.9 MB/s  0:00:00
Downloading filelock-3.32.3-py3-none-any.whl (98 kB)
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Downloading torch-2.13.0-cp313-cp313-manylinux_2_28_x86_64.whl (526.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/526.6 MB ? eta -:--:--

   ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/526.6 MB 117.1 MB/s eta 0:00:05

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/526.6 MB 114.4 MB/s eta 0:00:05

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.0/526.6 MB 114.6 MB/s eta 0:00:04

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.6/526.6 MB 114.7 MB/s eta 0:00:04

   ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/526.6 MB 114.9 MB/s eta 0:00:04

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/526.6 MB 114.3 MB/s eta 0:00:04

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/526.6 MB 114.0 MB/s eta 0:00:04

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 185.9/526.6 MB 114.1 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 209.5/526.6 MB 114.1 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 232.3/526.6 MB 114.0 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━ 255.6/526.6 MB 113.9 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 279.2/526.6 MB 113.6 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 302.8/526.6 MB 113.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 326.1/526.6 MB 114.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 349.4/526.6 MB 114.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 373.0/526.6 MB 114.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 396.4/526.6 MB 114.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 419.7/526.6 MB 114.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 443.0/526.6 MB 114.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 465.6/526.6 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 488.9/526.6 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 491.5/526.6 MB 114.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 503.1/526.6 MB 101.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 526.4/526.6 MB 101.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 61.8 MB/s  0:00:06
Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl (2.5 kB)
Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/366.2 MB ? eta -:--:--

   ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/366.2 MB 112.1 MB/s eta 0:00:04

   ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/366.2 MB 112.1 MB/s eta 0:00:03

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/366.2 MB 112.7 MB/s eta 0:00:03

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/366.2 MB 113.3 MB/s eta 0:00:03

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/366.2 MB 113.1 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/366.2 MB 113.4 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 161.5/366.2 MB 113.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 185.3/366.2 MB 113.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 208.7/366.2 MB 113.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 232.0/366.2 MB 113.3 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━ 255.6/366.2 MB 113.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 278.9/366.2 MB 113.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 302.5/366.2 MB 113.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━ 325.8/366.2 MB 114.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 349.4/366.2 MB 114.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 74.3 MB/s  0:00:04

Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/170.1 MB ? eta -:--:--

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/170.1 MB 116.4 MB/s eta 0:00:02

   ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/170.1 MB 114.6 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 69.7/170.1 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 93.1/170.1 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 116.4/170.1 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 139.7/170.1 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 162.5/170.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 170.1/170.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 170.1/170.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 170.1/170.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 81.4 MB/s  0:00:02
Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/206.0 MB ? eta -:--:--

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/206.0 MB 115.9 MB/s eta 0:00:02

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/206.0 MB 115.6 MB/s eta 0:00:02

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/206.0 MB 115.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 93.6/206.0 MB 115.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 117.2/206.0 MB 115.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 140.8/206.0 MB 115.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 163.3/206.0 MB 114.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 186.4/206.0 MB 114.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 205.8/206.0 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 205.8/206.0 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 205.8/206.0 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 205.8/206.0 MB 114.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 81.0 MB/s  0:00:02
Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/60.4 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/60.4 MB 115.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 46.4/60.4 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 60.3/60.4 MB 114.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 70.9 MB/s  0:00:00
Downloading triton-3.7.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (197.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/197.7 MB ? eta -:--:--

   ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.8/197.7 MB 114.6 MB/s eta 0:00:02

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/197.7 MB 112.2 MB/s eta 0:00:02

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/197.7 MB 111.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 91.0/197.7 MB 111.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 114.0/197.7 MB 112.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 136.8/197.7 MB 112.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 160.4/197.7 MB 112.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 183.2/197.7 MB 112.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 197.7/197.7 MB 112.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 197.7/197.7 MB 112.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 197.7/197.7 MB 112.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 86.8 MB/s  0:00:02
Downloading cuda_bindings-13.3.1-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/6.5 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 6.3/6.5 MB 118.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 24.6 MB/s  0:00:00
Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/423.1 MB ? eta -:--:--

   ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/423.1 MB 115.9 MB/s eta 0:00:04

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/423.1 MB 113.8 MB/s eta 0:00:04

   ━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/423.1 MB 113.0 MB/s eta 0:00:04

   ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.5/423.1 MB 112.6 MB/s eta 0:00:03

   ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.3/423.1 MB 112.4 MB/s eta 0:00:03

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/423.1 MB 112.5 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 160.7/423.1 MB 112.8 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 183.8/423.1 MB 112.7 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 207.1/423.1 MB 112.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━ 230.4/423.1 MB 113.2 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 253.8/423.1 MB 113.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 277.3/423.1 MB 113.3 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 300.9/423.1 MB 113.5 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 323.7/423.1 MB 113.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 347.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 370.1/423.1 MB 114.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 393.5/423.1 MB 114.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 416.3/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 73.5 MB/s  0:00:04
Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/10.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 55.2 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/90.2 MB ? eta -:--:--

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/90.2 MB 116.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 46.4/90.2 MB 115.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 69.5/90.2 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 90.2/90.2 MB 112.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 86.4 MB/s  0:00:01
Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.2 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 17.8 MB/s  0:00:00
Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/214.1 MB ? eta -:--:--

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/214.1 MB 112.4 MB/s eta 0:00:02

   ━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/214.1 MB 112.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/214.1 MB 112.8 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 91.8/214.1 MB 113.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 115.1/214.1 MB 113.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 138.4/214.1 MB 113.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 161.7/214.1 MB 113.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 184.3/214.1 MB 113.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 207.4/214.1 MB 113.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 213.9/214.1 MB 113.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 213.9/214.1 MB 113.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 213.9/214.1 MB 113.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 80.5 MB/s  0:00:02
Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.2 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 80.5 MB/s  0:00:00
Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/59.5 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/59.5 MB 115.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 45.6/59.5 MB 112.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 59.5/59.5 MB 113.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 77.5 MB/s  0:00:00
Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/200.9 MB ? eta -:--:--

   ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/200.9 MB 117.1 MB/s eta 0:00:02

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/200.9 MB 116.3 MB/s eta 0:00:02

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/200.9 MB 115.7 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 93.6/200.9 MB 115.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 117.2/200.9 MB 115.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━ 140.8/200.9 MB 115.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 163.8/200.9 MB 115.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 186.9/200.9 MB 115.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 200.8/200.9 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 200.8/200.9 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 200.8/200.9 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 200.8/200.9 MB 114.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 78.8 MB/s  0:00:02
Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/145.9 MB ? eta -:--:--

   ━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/145.9 MB 115.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/145.9 MB 115.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 69.5/145.9 MB 114.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 93.1/145.9 MB 113.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 115.9/145.9 MB 113.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 139.2/145.9 MB 113.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 145.8/145.9 MB 114.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 98.0 MB/s  0:00:01
Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/40.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 23.3/40.7 MB 116.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 40.6/40.7 MB 116.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 95.0 MB/s  0:00:00
Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading cuda_pathfinder-1.6.1-py3-none-any.whl (60 kB)

Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 79.0 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/6.3 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 95.7 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 62.4 MB/s  0:00:00
Downloading typer-0.27.1-py3-none-any.whl (122 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)

Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, triton, sympy, shellingham, safetensors, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, networkx, hf-xet, filelock, cuda-pathfinder, nvidia-cusparse, nvidia-cufft, nvidia-cublas, cuda-bindings, typer, nvidia-cusolver, nvidia-cudnn-cu13, huggingface-hub, tokenizers, transformers, torch, sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/32 [nvidia-cusparselt-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/32 [nvidia-cusparselt-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/32 [nvidia-cusparselt-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/32 [nvidia-cusparselt-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/32 [nvidia-cusparselt-cu13]

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/32 [mpmath]

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/32 [mpmath]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/32 [triton]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/32 [sympy]

   ━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/32 [shellingham]

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/32 [nvidia-nvshmem-cu13]

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/32 [nvidia-nvshmem-cu13]

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/32 [nvidia-nvjitlink]

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/32 [nvidia-nvjitlink]

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/32 [nvidia-nvjitlink]

  Attempting uninstall: nvidia-nccl-cu13
    Found existing installation: nvidia-nccl-cu13 2.31.2
    Uninstalling nvidia-nccl-cu13-2.31.2:
   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

      Successfully uninstalled nvidia-nccl-cu13-2.31.2
   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/32 [nvidia-nccl-cu13]

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/32 [nvidia-curand]

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/32 [nvidia-curand]

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/32 [nvidia-curand]

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 13/32 [nvidia-cuda-runtime]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 14/32 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 15/32 [nvidia-cuda-cupti]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 16/32 [networkx]

   ━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━ 17/32 [hf-xet]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 20/32 [nvidia-cusparse]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 20/32 [nvidia-cusparse]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 20/32 [nvidia-cusparse]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 20/32 [nvidia-cusparse]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 21/32 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 22/32 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 24/32 [typer]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 25/32 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 25/32 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 25/32 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 25/32 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 25/32 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 26/32 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 27/32 [huggingface-hub]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 27/32 [huggingface-hub]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 27/32 [huggingface-hub]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 28/32 [tokenizers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 29/32 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 30/32 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 31/32 [sentence-transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 31/32 [sentence-transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32/32 [sentence-transformers]

Successfully installed cuda-bindings-13.3.1 cuda-pathfinder-1.6.1 cuda-toolkit-13.0.3.0 filelock-3.32.3 hf-xet-1.6.0 huggingface-hub-1.27.0 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.3.33 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 safetensors-0.8.0 sentence-transformers-5.7.0 shellingham-1.5.4 sympy-1.14.0 tokenizers-0.22.2 torch-2.13.0 transformers-5.15.0 triton-3.7.1 typer-0.27.1

/opt/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
def load_categories(path="categories.yaml"):
    with open(path, "r", encoding="utf-8") as f:
        cats = yaml.safe_load(f)

    flat = []  # liste plate (catégorie, sous-catégorie, texte de référence)
    for cat in cats:
        for sub in cat.get("subcategories", []):
            flat.append({
                "category": cat["slug"],
                "subcategory": sub["slug"],
                "label": f"{cat['label']} > {sub['label']}",
                "text": f"{cat['description']}. {sub['description']}",
            })
    return flat

In [14]:
def classify_df(df, categories_path="categories.yaml",
                 model_name="paraphrase-multilingual-mpnet-base-v2",
                 threshold=0.25):
    model = SentenceTransformer(model_name)
    cats = load_categories(categories_path)

    # Embeddings des catégories (une seule fois)
    cat_texts = [c["text"] for c in cats]
    cat_embeddings = model.encode(cat_texts, convert_to_tensor=True)

    # Embeddings des datasets (titre + description + tags)
    doc_texts = (
        df["title"].fillna("") + ". " +
        df["description"].fillna("") + ". " +
        df["tags"].apply(lambda t: " ".join(t) if isinstance(t, list) else "")
    ).tolist()
    doc_embeddings = model.encode(doc_texts, convert_to_tensor=True,
                                   batch_size=64, show_progress_bar=True)

    # Similarité cosinus dataset x catégorie
    sims = util.cos_sim(doc_embeddings, cat_embeddings).cpu().numpy()

    best_idx = sims.argmax(axis=1)
    best_score = sims.max(axis=1)

    df = df.copy()
    df["category"] = [cats[i]["category"] if s >= threshold else "" for i, s in zip(best_idx, best_score)]
    df["subcategory"] = [cats[i]["subcategory"] if s >= threshold else "" for i, s in zip(best_idx, best_score)]
    df["category_score"] = best_score
    return df

In [16]:
# Filtrer les datasets qui ne sont PAS dans le domaine / garder ceux qui contiennent au moins 1 mot-clé d'une liste mobilité

In [15]:
import pandas as pd
import re

In [19]:

dsdatagouv = pd.read_csv("export-dataset-20260817-055836.csv", sep=";")

In [37]:
# le catalogue des datasets contient aussi ceux qui sont archivsé : on ne va pas les traiter (on passe ainsi de 130k à 73k datasets)
dsdatagouv=dsdatagouv[dsdatagouv["archived"] == "False"]

In [38]:
dsdatagouv.shape

(73886, 47)

In [17]:
keywords = [
    "transport", "mobilité", "route", "passager", "fret", "parking", "stationnement", "voirie", "accessibilité", "enquête", "horaire", "calendrier", 
    "vélo", "trafic", "piéton", "voiture", "véhicule", "carburant", "accident", "sécurité routière", "train", "transport public", "avion", "fluvial", "maritime",
    "covoiturage", "autopartage", "bruit", "qualité de l'air"
]

In [39]:
# Construire un pattern regex : mot1|mot2|mot3...
pattern = "|".join(re.escape(kw) for kw in keywords)

# Concaténer title + description pour chercher dans les deux
text = (
    dsdatagouv["title"].fillna("") + " " + dsdatagouv["description"].fillna("")
)

In [40]:
mask = text.str.contains(pattern, case=False, na=False, regex=True)
dsdatagouv_mob = dsdatagouv[mask].copy()

In [44]:
# la recherche des chaines prend 2' ; on divise le nb de datasets par 5 environ
dsdatagouv_mob.shape

(16123, 47)

In [45]:
dsdatagouv_mob.to_parquet('datagouvds2.parquet')

In [ ]:
# étape suivante : classer avec une modèle de langage les entrées de la table des datasets selon une liste de catégories métier mobilité et sous-catégories

In [53]:
dsdatagouv_mob_class = classify_df(dsdatagouv_mob,categories_path="catalogue_datamobilite.yaml")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2400.36it/s]

Batches:   0%|          | 0/252 [00:00<?, ?it/s]

Batches:   0%|          | 1/252 [00:06<26:11,  6.26s/it]

Batches:   1%|          | 2/252 [00:10<22:11,  5.33s/it]

Batches:   1%|          | 3/252 [00:15<21:19,  5.14s/it]

Batches:   2%|▏         | 4/252 [00:21<21:40,  5.24s/it]

Batches:   2%|▏         | 5/252 [00:26<21:49,  5.30s/it]

Batches:   2%|▏         | 6/252 [00:31<21:06,  5.15s/it]

Batches:   3%|▎         | 7/252 [00:36<20:52,  5.11s/it]

Batches:   3%|▎         | 8/252 [00:41<21:10,  5.21s/it]

Batches:   4%|▎         | 9/252 [00:47<21:34,  5.33s/it]

Batches:   4%|▍         | 10/252 [00:52<21:14,  5.26s/it]

Batches:   4%|▍         | 11/252 [00:57<20:32,  5.11s/it]

Batches:   5%|▍         | 12/252 [01:02<20:01,  5.01s/it]

Batches:   5%|▌         | 13/252 [01:07<20:11,  5.07s/it]

Batches:   6%|▌         | 14/252 [01:11<19:21,  4.88s/it]

Batches:   6%|▌         | 15/252 [01:16<18:52,  4.78s/it]

Batches:   6%|▋         | 16/252 [01:21<18:45,  4.77s/it]

Batches:   7%|▋         | 17/252 [01:26<19:10,  4.90s/it]

Batches:   7%|▋         | 18/252 [01:30<18:10,  4.66s/it]

Batches:   8%|▊         | 19/252 [01:34<17:13,  4.43s/it]

Batches:   8%|▊         | 20/252 [01:38<17:19,  4.48s/it]

Batches:   8%|▊         | 21/252 [01:43<17:08,  4.45s/it]

Batches:   9%|▊         | 22/252 [01:47<17:08,  4.47s/it]

Batches:   9%|▉         | 23/252 [01:52<16:52,  4.42s/it]

Batches:  10%|▉         | 24/252 [01:56<16:25,  4.32s/it]

Batches:  10%|▉         | 25/252 [02:00<16:31,  4.37s/it]

Batches:  10%|█         | 26/252 [02:05<16:57,  4.50s/it]

Batches:  11%|█         | 27/252 [02:10<17:20,  4.63s/it]

Batches:  11%|█         | 28/252 [02:15<17:40,  4.74s/it]

Batches:  12%|█▏        | 29/252 [02:19<17:00,  4.57s/it]

Batches:  12%|█▏        | 30/252 [02:23<16:17,  4.40s/it]

Batches:  12%|█▏        | 31/252 [02:27<15:26,  4.19s/it]

Batches:  13%|█▎        | 32/252 [02:30<14:43,  4.01s/it]

Batches:  13%|█▎        | 33/252 [02:34<13:58,  3.83s/it]

Batches:  13%|█▎        | 34/252 [02:38<14:31,  4.00s/it]

Batches:  14%|█▍        | 35/252 [02:42<14:15,  3.94s/it]

Batches:  14%|█▍        | 36/252 [02:46<14:14,  3.95s/it]

Batches:  15%|█▍        | 37/252 [02:50<14:14,  3.97s/it]

Batches:  15%|█▌        | 38/252 [02:54<13:59,  3.92s/it]

Batches:  15%|█▌        | 39/252 [02:58<13:53,  3.91s/it]

Batches:  16%|█▌        | 40/252 [03:01<13:29,  3.82s/it]

Batches:  16%|█▋        | 41/252 [03:05<13:11,  3.75s/it]

Batches:  17%|█▋        | 42/252 [03:09<13:17,  3.80s/it]

Batches:  17%|█▋        | 43/252 [03:13<13:21,  3.83s/it]

Batches:  17%|█▋        | 44/252 [03:17<13:13,  3.82s/it]

Batches:  18%|█▊        | 45/252 [03:21<13:21,  3.87s/it]

Batches:  18%|█▊        | 46/252 [03:24<13:07,  3.82s/it]

Batches:  19%|█▊        | 47/252 [03:29<14:27,  4.23s/it]

Batches:  19%|█▉        | 48/252 [03:34<14:33,  4.28s/it]

Batches:  19%|█▉        | 49/252 [03:38<14:37,  4.32s/it]

Batches:  20%|█▉        | 50/252 [03:42<14:12,  4.22s/it]

Batches:  20%|██        | 51/252 [03:46<14:01,  4.19s/it]

Batches:  21%|██        | 52/252 [03:50<13:40,  4.10s/it]

Batches:  21%|██        | 53/252 [03:54<13:40,  4.12s/it]

Batches:  21%|██▏       | 54/252 [03:59<13:48,  4.19s/it]

Batches:  22%|██▏       | 55/252 [04:03<13:38,  4.16s/it]

Batches:  22%|██▏       | 56/252 [04:07<13:43,  4.20s/it]

Batches:  23%|██▎       | 57/252 [04:12<14:02,  4.32s/it]

Batches:  23%|██▎       | 58/252 [04:16<14:02,  4.34s/it]

Batches:  23%|██▎       | 59/252 [04:21<14:19,  4.45s/it]

Batches:  24%|██▍       | 60/252 [04:26<14:34,  4.55s/it]

Batches:  24%|██▍       | 61/252 [04:30<14:22,  4.52s/it]

Batches:  25%|██▍       | 62/252 [04:35<14:21,  4.53s/it]

Batches:  25%|██▌       | 63/252 [04:40<14:43,  4.67s/it]

Batches:  25%|██▌       | 64/252 [04:45<15:02,  4.80s/it]

Batches:  26%|██▌       | 65/252 [04:50<15:21,  4.93s/it]

Batches:  26%|██▌       | 66/252 [04:55<15:08,  4.88s/it]

Batches:  27%|██▋       | 67/252 [05:00<15:15,  4.95s/it]

Batches:  27%|██▋       | 68/252 [05:05<15:02,  4.90s/it]

Batches:  27%|██▋       | 69/252 [05:10<15:23,  5.05s/it]

Batches:  28%|██▊       | 70/252 [05:15<15:20,  5.06s/it]

Batches:  28%|██▊       | 71/252 [05:21<15:35,  5.17s/it]

Batches:  29%|██▊       | 72/252 [05:26<16:03,  5.35s/it]

Batches:  29%|██▉       | 73/252 [05:31<15:39,  5.25s/it]

Batches:  29%|██▉       | 74/252 [05:37<15:31,  5.23s/it]

Batches:  30%|██▉       | 75/252 [05:42<15:24,  5.22s/it]

Batches:  30%|███       | 76/252 [05:47<15:25,  5.26s/it]

Batches:  31%|███       | 77/252 [05:52<15:22,  5.27s/it]

Batches:  31%|███       | 78/252 [05:58<15:17,  5.27s/it]

Batches:  31%|███▏      | 79/252 [06:04<15:50,  5.49s/it]

Batches:  32%|███▏      | 80/252 [06:09<15:54,  5.55s/it]

Batches:  32%|███▏      | 81/252 [06:15<15:32,  5.45s/it]

Batches:  33%|███▎      | 82/252 [06:20<15:09,  5.35s/it]

Batches:  33%|███▎      | 83/252 [06:24<14:25,  5.12s/it]

Batches:  33%|███▎      | 84/252 [06:29<13:59,  5.00s/it]

Batches:  34%|███▎      | 85/252 [06:34<13:59,  5.03s/it]

Batches:  34%|███▍      | 86/252 [06:39<14:02,  5.08s/it]

Batches:  35%|███▍      | 87/252 [06:44<14:03,  5.11s/it]

Batches:  35%|███▍      | 88/252 [06:49<13:52,  5.08s/it]

Batches:  35%|███▌      | 89/252 [06:55<13:49,  5.09s/it]

Batches:  36%|███▌      | 90/252 [07:00<13:57,  5.17s/it]

Batches:  36%|███▌      | 91/252 [07:05<14:09,  5.28s/it]

Batches:  37%|███▋      | 92/252 [07:12<14:44,  5.53s/it]

Batches:  37%|███▋      | 93/252 [07:16<14:03,  5.30s/it]

Batches:  37%|███▋      | 94/252 [07:21<13:43,  5.21s/it]

Batches:  38%|███▊      | 95/252 [07:26<13:19,  5.09s/it]

Batches:  38%|███▊      | 96/252 [07:31<13:08,  5.06s/it]

Batches:  38%|███▊      | 97/252 [07:36<12:57,  5.01s/it]

Batches:  39%|███▉      | 98/252 [07:41<12:59,  5.06s/it]

Batches:  39%|███▉      | 99/252 [07:47<13:06,  5.14s/it]

Batches:  40%|███▉      | 100/252 [07:52<13:17,  5.24s/it]

Batches:  40%|████      | 101/252 [07:58<13:23,  5.32s/it]

Batches:  40%|████      | 102/252 [08:03<13:08,  5.26s/it]

Batches:  41%|████      | 103/252 [08:08<13:00,  5.24s/it]

Batches:  41%|████▏     | 104/252 [08:13<12:40,  5.14s/it]

Batches:  42%|████▏     | 105/252 [08:17<12:11,  4.97s/it]

Batches:  42%|████▏     | 106/252 [08:22<12:13,  5.02s/it]

Batches:  42%|████▏     | 107/252 [08:27<12:07,  5.02s/it]

Batches:  43%|████▎     | 108/252 [08:32<11:35,  4.83s/it]

Batches:  43%|████▎     | 109/252 [08:37<11:42,  4.91s/it]

Batches:  44%|████▎     | 110/252 [08:42<11:32,  4.88s/it]

Batches:  44%|████▍     | 111/252 [08:46<11:11,  4.76s/it]

Batches:  44%|████▍     | 112/252 [08:52<11:27,  4.91s/it]

Batches:  45%|████▍     | 113/252 [08:56<11:07,  4.80s/it]

Batches:  45%|████▌     | 114/252 [09:01<11:09,  4.85s/it]

Batches:  46%|████▌     | 115/252 [09:06<11:16,  4.94s/it]

Batches:  46%|████▌     | 116/252 [09:11<11:16,  4.98s/it]

Batches:  46%|████▋     | 117/252 [09:16<11:17,  5.02s/it]

Batches:  47%|████▋     | 118/252 [09:21<11:03,  4.95s/it]

Batches:  47%|████▋     | 119/252 [09:26<10:44,  4.85s/it]

Batches:  48%|████▊     | 120/252 [09:31<10:50,  4.93s/it]

Batches:  48%|████▊     | 121/252 [09:36<10:51,  4.97s/it]

Batches:  48%|████▊     | 122/252 [09:41<10:47,  4.98s/it]

Batches:  49%|████▉     | 123/252 [09:46<10:26,  4.86s/it]

Batches:  49%|████▉     | 124/252 [09:50<10:17,  4.82s/it]

Batches:  50%|████▉     | 125/252 [09:55<09:56,  4.69s/it]

Batches:  50%|█████     | 126/252 [09:59<09:51,  4.69s/it]

Batches:  50%|█████     | 127/252 [10:04<09:46,  4.69s/it]

Batches:  51%|█████     | 128/252 [10:09<09:37,  4.66s/it]

Batches:  51%|█████     | 129/252 [10:14<09:46,  4.77s/it]

Batches:  52%|█████▏    | 130/252 [10:18<09:25,  4.63s/it]

Batches:  52%|█████▏    | 131/252 [10:22<08:42,  4.32s/it]

Batches:  52%|█████▏    | 132/252 [10:26<08:30,  4.25s/it]

Batches:  53%|█████▎    | 133/252 [10:30<08:21,  4.21s/it]

Batches:  53%|█████▎    | 134/252 [10:34<08:09,  4.15s/it]

Batches:  54%|█████▎    | 135/252 [10:38<08:17,  4.25s/it]

Batches:  54%|█████▍    | 136/252 [10:42<08:11,  4.24s/it]

Batches:  54%|█████▍    | 137/252 [10:47<08:05,  4.22s/it]

Batches:  55%|█████▍    | 138/252 [10:51<07:57,  4.19s/it]

Batches:  55%|█████▌    | 139/252 [10:55<07:56,  4.21s/it]

Batches:  56%|█████▌    | 140/252 [10:59<07:55,  4.25s/it]

Batches:  56%|█████▌    | 141/252 [11:03<07:43,  4.17s/it]

Batches:  56%|█████▋    | 142/252 [11:08<08:08,  4.44s/it]

Batches:  57%|█████▋    | 143/252 [11:13<08:04,  4.44s/it]

Batches:  57%|█████▋    | 144/252 [11:17<08:04,  4.49s/it]

Batches:  58%|█████▊    | 145/252 [11:22<07:56,  4.46s/it]

Batches:  58%|█████▊    | 146/252 [11:26<07:43,  4.37s/it]

Batches:  58%|█████▊    | 147/252 [11:30<07:34,  4.33s/it]

Batches:  59%|█████▊    | 148/252 [11:34<07:19,  4.23s/it]

Batches:  59%|█████▉    | 149/252 [11:38<07:14,  4.22s/it]

Batches:  60%|█████▉    | 150/252 [11:43<07:15,  4.27s/it]

Batches:  60%|█████▉    | 151/252 [11:47<07:08,  4.25s/it]

Batches:  60%|██████    | 152/252 [11:51<07:00,  4.21s/it]

Batches:  61%|██████    | 153/252 [11:55<06:50,  4.15s/it]

Batches:  61%|██████    | 154/252 [12:00<06:56,  4.25s/it]

Batches:  62%|██████▏   | 155/252 [12:04<06:50,  4.24s/it]

Batches:  62%|██████▏   | 156/252 [12:08<06:50,  4.28s/it]

Batches:  62%|██████▏   | 157/252 [12:13<06:56,  4.39s/it]

Batches:  63%|██████▎   | 158/252 [12:17<06:55,  4.42s/it]

Batches:  63%|██████▎   | 159/252 [12:22<06:58,  4.49s/it]

Batches:  63%|██████▎   | 160/252 [12:26<06:50,  4.46s/it]

Batches:  64%|██████▍   | 161/252 [12:31<06:39,  4.39s/it]

Batches:  64%|██████▍   | 162/252 [12:35<06:35,  4.40s/it]

Batches:  65%|██████▍   | 163/252 [12:40<06:34,  4.43s/it]

Batches:  65%|██████▌   | 164/252 [12:44<06:28,  4.42s/it]

Batches:  65%|██████▌   | 165/252 [12:48<06:26,  4.44s/it]

Batches:  66%|██████▌   | 166/252 [12:53<06:21,  4.44s/it]

Batches:  66%|██████▋   | 167/252 [12:58<06:37,  4.68s/it]

Batches:  67%|██████▋   | 168/252 [13:03<06:28,  4.63s/it]

Batches:  67%|██████▋   | 169/252 [13:07<06:14,  4.51s/it]

Batches:  67%|██████▋   | 170/252 [13:12<06:16,  4.59s/it]

Batches:  68%|██████▊   | 171/252 [13:17<06:21,  4.71s/it]

Batches:  68%|██████▊   | 172/252 [13:21<06:14,  4.68s/it]

Batches:  69%|██████▊   | 173/252 [13:26<06:00,  4.57s/it]

Batches:  69%|██████▉   | 174/252 [13:30<06:01,  4.63s/it]

Batches:  69%|██████▉   | 175/252 [13:34<05:44,  4.48s/it]

Batches:  70%|██████▉   | 176/252 [13:39<05:34,  4.40s/it]

Batches:  70%|███████   | 177/252 [13:43<05:17,  4.24s/it]

Batches:  71%|███████   | 178/252 [13:47<05:26,  4.41s/it]

Batches:  71%|███████   | 179/252 [13:51<05:14,  4.31s/it]

Batches:  71%|███████▏  | 180/252 [13:56<05:06,  4.26s/it]

Batches:  72%|███████▏  | 181/252 [14:00<04:59,  4.21s/it]

Batches:  72%|███████▏  | 182/252 [14:03<04:43,  4.06s/it]

Batches:  73%|███████▎  | 183/252 [14:07<04:40,  4.06s/it]

Batches:  73%|███████▎  | 184/252 [14:12<04:49,  4.26s/it]

Batches:  73%|███████▎  | 185/252 [14:17<04:47,  4.29s/it]

Batches:  74%|███████▍  | 186/252 [14:20<04:35,  4.18s/it]

Batches:  74%|███████▍  | 187/252 [14:24<04:26,  4.09s/it]

Batches:  75%|███████▍  | 188/252 [14:29<04:35,  4.31s/it]

Batches:  75%|███████▌  | 189/252 [14:33<04:21,  4.15s/it]

Batches:  75%|███████▌  | 190/252 [14:37<04:11,  4.05s/it]

Batches:  76%|███████▌  | 191/252 [14:40<03:57,  3.89s/it]

Batches:  76%|███████▌  | 192/252 [14:44<03:50,  3.83s/it]

Batches:  77%|███████▋  | 193/252 [14:48<03:45,  3.82s/it]

Batches:  77%|███████▋  | 194/252 [14:51<03:39,  3.79s/it]

Batches:  77%|███████▋  | 195/252 [14:55<03:29,  3.67s/it]

Batches:  78%|███████▊  | 196/252 [14:58<03:20,  3.59s/it]

Batches:  78%|███████▊  | 197/252 [15:02<03:12,  3.50s/it]

Batches:  79%|███████▊  | 198/252 [15:05<03:15,  3.61s/it]

Batches:  79%|███████▉  | 199/252 [15:09<03:10,  3.59s/it]

Batches:  79%|███████▉  | 200/252 [15:12<03:03,  3.52s/it]

Batches:  80%|███████▉  | 201/252 [15:15<02:53,  3.40s/it]

Batches:  80%|████████  | 202/252 [15:19<02:47,  3.35s/it]

Batches:  81%|████████  | 203/252 [15:22<02:38,  3.24s/it]

Batches:  81%|████████  | 204/252 [15:25<02:35,  3.25s/it]

Batches:  81%|████████▏ | 205/252 [15:29<02:38,  3.36s/it]

Batches:  82%|████████▏ | 206/252 [15:32<02:35,  3.38s/it]

Batches:  82%|████████▏ | 207/252 [15:35<02:30,  3.34s/it]

Batches:  83%|████████▎ | 208/252 [15:39<02:26,  3.33s/it]

Batches:  83%|████████▎ | 209/252 [15:42<02:19,  3.24s/it]

Batches:  83%|████████▎ | 210/252 [15:45<02:14,  3.20s/it]

Batches:  84%|████████▎ | 211/252 [15:48<02:10,  3.19s/it]

Batches:  84%|████████▍ | 212/252 [15:51<02:03,  3.08s/it]

Batches:  85%|████████▍ | 213/252 [15:53<01:54,  2.93s/it]

Batches:  85%|████████▍ | 214/252 [15:56<01:50,  2.90s/it]

Batches:  85%|████████▌ | 215/252 [15:59<01:46,  2.87s/it]

Batches:  86%|████████▌ | 216/252 [16:01<01:39,  2.76s/it]

Batches:  86%|████████▌ | 217/252 [16:04<01:34,  2.70s/it]

Batches:  87%|████████▋ | 218/252 [16:07<01:34,  2.77s/it]

Batches:  87%|████████▋ | 219/252 [16:09<01:27,  2.65s/it]

Batches:  87%|████████▋ | 220/252 [16:12<01:21,  2.55s/it]

Batches:  88%|████████▊ | 221/252 [16:14<01:17,  2.50s/it]

Batches:  88%|████████▊ | 222/252 [16:16<01:12,  2.41s/it]

Batches:  88%|████████▊ | 223/252 [16:19<01:10,  2.44s/it]

Batches:  89%|████████▉ | 224/252 [16:21<01:05,  2.34s/it]

Batches:  89%|████████▉ | 225/252 [16:23<01:02,  2.30s/it]

Batches:  90%|████████▉ | 226/252 [16:25<00:58,  2.23s/it]

Batches:  90%|█████████ | 227/252 [16:27<00:55,  2.23s/it]

Batches:  90%|█████████ | 228/252 [16:29<00:52,  2.18s/it]

Batches:  91%|█████████ | 229/252 [16:31<00:47,  2.08s/it]

Batches:  91%|█████████▏| 230/252 [16:33<00:44,  2.02s/it]

Batches:  92%|█████████▏| 231/252 [16:35<00:40,  1.95s/it]

Batches:  92%|█████████▏| 232/252 [16:37<00:38,  1.90s/it]

Batches:  92%|█████████▏| 233/252 [16:39<00:37,  1.96s/it]

Batches:  93%|█████████▎| 234/252 [16:40<00:33,  1.85s/it]

Batches:  93%|█████████▎| 235/252 [16:42<00:31,  1.87s/it]

Batches:  94%|█████████▎| 236/252 [16:44<00:28,  1.79s/it]

Batches:  94%|█████████▍| 237/252 [16:45<00:26,  1.74s/it]

Batches:  94%|█████████▍| 238/252 [16:47<00:24,  1.76s/it]

Batches:  95%|█████████▍| 239/252 [16:49<00:22,  1.74s/it]

Batches:  95%|█████████▌| 240/252 [16:51<00:20,  1.73s/it]

Batches:  96%|█████████▌| 241/252 [16:52<00:18,  1.69s/it]

Batches:  96%|█████████▌| 242/252 [16:54<00:17,  1.72s/it]

Batches:  96%|█████████▋| 243/252 [16:56<00:15,  1.74s/it]

Batches:  97%|█████████▋| 244/252 [16:58<00:14,  1.82s/it]

Batches:  97%|█████████▋| 245/252 [17:00<00:12,  1.85s/it]

Batches:  98%|█████████▊| 246/252 [17:01<00:10,  1.80s/it]

Batches:  98%|█████████▊| 247/252 [17:03<00:09,  1.80s/it]

Batches:  98%|█████████▊| 248/252 [17:05<00:07,  1.89s/it]

Batches:  99%|█████████▉| 249/252 [17:07<00:05,  1.87s/it]

Batches:  99%|█████████▉| 250/252 [17:08<00:03,  1.63s/it]

Batches: 100%|█████████▉| 251/252 [17:09<00:01,  1.48s/it]

Batches: 100%|██████████| 252/252 [17:11<00:00,  1.42s/it]

Batches: 100%|██████████| 252/252 [17:11<00:00,  4.09s/it]

In [47]:
dsdatagouv_mob_class

,id,title,slug,acronym,url,organization,organization_id,owner,owner_id,description,...,metric.reuses,metric.reuses_by_months,metric.dataservices,metric.followers,metric.followers_by_months,metric.views,metric.resources_downloads,category,subcategory,category_score
0,6a826c488feaf1584f1dba40,Recueils des actes administratifs des préfectures,recueils-des-actes-administratifs-des-prefectures,RAA,https://www.data.gouv.fr/datasets/recueils-des...,NaN,NaN,sebastien-gunther,578bec4388ee3879bb43efac,Ce jeu de données recense les **recueils des a...,...,0,0,0,0,0,0,0.0,trafic_routier,capteurs_trafic,0.375631
7,6a7faceb92d679122704ef32,Horaires de passage théoriques aux arrêts,horaires-de-passage-theoriques-aux-arrets-3,NaN,https://www.data.gouv.fr/datasets/horaires-de-...,Twisto,5c09189f8b4c414a8d02298e,NaN,NaN,NaN,...,0,0,2,0,0,0,0.0,trafic_routier,capteurs_trafic,0.473291
12,6a7f1d71f5a0602f732de662,Mobilité- Stationnement des parkings en temps ...,mobilite-stationnement-des-parkings-en-temps-reel,NaN,https://www.data.gouv.fr/datasets/mobilite-sta...,Grand Poitiers Open Data,54da1f52c751df59f7467389,NaN,NaN,Ce jeu de données permet de connaitre l'occupa...,...,0,0,1,0,0,103,0.0,trafic_routier,capteurs_trafic,0.430661
13,6a7f1b68be6d17e8334d6314,Voirie - Places handicapées GIG / GIC - Grand ...,voirie-places-handicapees-gig-gic-grand-poitie...,NaN,https://www.data.gouv.fr/datasets/voirie-place...,Grand Poitiers Open Data,54da1f52c751df59f7467389,NaN,NaN,Ce jeu de données provient du SIG et est direc...,...,0,0,1,0,0,111,0.0,trafic_routier,capteurs_trafic,0.314052
20,6a7e87b12d75648c1e04ef1d,Réglementation de boisement - PUY-DE-DÔME,reglementation-de-boisement-puy-de-dome-2,NaN,https://www.data.gouv.fr/datasets/reglementati...,Direction Départementale des Territoire du Puy...,565f741788ee380296e72046,NaN,NaN,En vertu de l'article L126-1 du code rural et ...,...,0,0,1,0,0,99,0.0,trafic_routier,capteurs_trafic,0.384918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130026,5ce8899506e3e76c44d57ebb,Conseillers municipaux de Digne-les-Bains,conseillers-municipaux-de-digne-les-bains,NaN,https://www.data.gouv.fr/datasets/conseillers-...,Ville de Digne-les-Bains,534fffb8a3a7292c64a78149,NaN,NaN,Liste des conseillers municipaux de la ville d...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",4976,2793.0,trafic_routier,capteurs_trafic,0.352917
130028,5ce66e0d06e3e7682a625231,Evénements sportifs à Digne-les-Bains,evenements-sportifs-a-digne-les-bains,NaN,https://www.data.gouv.fr/datasets/evenements-s...,Ville de Digne-les-Bains,534fffb8a3a7292c64a78149,NaN,NaN,Calendrier de tous les événements sportifs de ...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",3416,509.0,trafic_routier,capteurs_trafic,0.292243
130029,5ce8899d06e3e76c3ed57ec4,Calendrier des événements culturels des saison...,calendrier-des-evenements-culturels-des-saison...,NaN,https://www.data.gouv.fr/datasets/calendrier-d...,Ville de Digne-les-Bains,534fffb8a3a7292c64a78149,NaN,NaN,Descriptif de la programmation culturelle prop...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",2004,268.0,trafic_routier,capteurs_trafic,0.280250
130138,602effc254337d92587ce5a3,"Véloroutes, Voies Vertes et Boucles Cyclodécou...",veloroutes-voies-vertes-et-boucles-cyclodecouv...,NaN,https://www.data.gouv.fr/datasets/veloroutes-v...,Département du Gard,5fd1e3ddd8016453bf402e4b,NaN,NaN,"Véloroutes, Voies Vertes et Boucles Cyclodécou...",...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",2643,485.0,trafic_routier,capteurs_trafic,0.428629
130284,602effc454337d92587ce5a6,Les mairies du Gard,les-mairies-du-gard,NaN,https://www.data.gouv.fr/datasets/les-mairies-...,Département du Gard,5fd1e3ddd8016453bf402e4b,NaN,NaN,Localisation des mairies du gard avec données ...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",5662,356.0,trafic_routier,capteurs_trafic,0.486842

In [54]:
dsdatagouv_mob_class[dsdatagouv_mob_class["category_score"]>0.6]

,id,title,slug,acronym,url,organization,organization_id,owner,owner_id,description,...,metric.reuses,metric.reuses_by_months,metric.dataservices,metric.followers,metric.followers_by_months,metric.views,metric.resources_downloads,category,subcategory,category_score
36,6a7d0997f2ee77d5f604eedd,Parcs d'activités - Transports,parcs-dactivites-transports,NaN,https://www.data.gouv.fr/datasets/parcs-dactiv...,Orléans Métropole,57ed2fe9c751df236179df72,NaN,NaN,Parcs d'activités - Transports,...,0,0,2,0,0,270,0.0,stationnement,stationnement_parc,0.643888
256,6a6be59d6a05df136d48fb84,Accessibilité aux stations de bus et tramway,accessibilite-aux-stations-de-bus-et-tramway-4,NaN,https://www.data.gouv.fr/datasets/accessibilit...,Twisto,5c09189f8b4c414a8d02298e,NaN,NaN,Liste des stations de bus et de tramway access...,...,0,0,2,0,0,354,8.0,stationnement,stationnement_voirie,0.600197
258,6a6be59c6a05df136d48fb82,Agence mobilités Twisto,agence-mobilites-twisto-3,NaN,https://www.data.gouv.fr/datasets/agence-mobil...,Twisto,5c09189f8b4c414a8d02298e,NaN,NaN,Adresse et coordonnées GPS de l'agence Mobilit...,...,0,0,2,0,0,297,6.0,trafic_routier,capteurs_trafic,0.680497
265,6a6be5986a05df136d48fb7b,Liste des emplacements d'autopartage,liste-des-emplacements-dautopartage-3,NaN,https://www.data.gouv.fr/datasets/liste-des-em...,Twisto,5c09189f8b4c414a8d02298e,NaN,NaN,Twisto Auto le service de voitures en autopart...,...,0,0,2,0,0,335,2.0,stationnement,stationnement_voirie,0.610663
268,6a6be5966a05df136d48fb78,Liste des stations Vélopark,liste-des-stations-velopark-3,NaN,https://www.data.gouv.fr/datasets/liste-des-st...,Twisto,5c09189f8b4c414a8d02298e,NaN,NaN,"Liste des stations Vélopark, comprenant l'adre...",...,0,0,2,0,0,306,3.0,stationnement,stationnement_voirie,0.600306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127408,5369a253a3a729239d2067fb,Trafic sur RD,trafic-sur-rd-oise,NaN,https://www.data.gouv.fr/datasets/trafic-sur-r...,Conseil général de l'Oise,534fff67a3a7292c64a77d7d,NaN,NaN,Le trafic routier est la mesure du nombre de v...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",13837,2220.0,trafic_routier,capteurs_trafic,0.642869
127488,5369a039a3a729239d2062fc,Stations d'auto partage,stations-d-auto-partage-tm,NaN,https://www.data.gouv.fr/datasets/stations-d-a...,Mairie de Toulouse,534fff8aa3a7292c64a77ecd,NaN,NaN,Localisation des emplacements de stationnement...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",4850,437.0,stationnement,stationnement_voirie,0.609757
128040,5369996da3a729239d20524e,Localisation des points d'arrêts des lignes ré...,localisation-des-points-d-arrets-des-lignes-re...,NaN,https://www.data.gouv.fr/datasets/localisation...,Conseil Départemental de la Gironde,534fff67a3a7292c64a77d83,NaN,NaN,Ce jeu de données fournit la localisation des ...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",3209,1623.0,trafic_routier,capteurs_trafic,0.613289
128854,536992d2a3a729239d204012,Détail des zones de stationnement,detail-des-zones-de-stationnement-30383267,NaN,https://www.data.gouv.fr/datasets/detail-des-z...,Coulommiers,534fff6ba3a7292c64a77da2,NaN,NaN,Détail des emplacements de stationnement sur l...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",0,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",2559,80.0,stationnement,stationnement_voirie,0.631112
129190,53699b6fa3a729239d20572d,Parc automobile par ministère en 2013,parc-automobile-par-ministere-en-2013,NaN,https://www.data.gouv.fr/datasets/parc-automob...,Ministères économiques et financiers,534fff8ea3a7292c64a77f02,NaN,NaN,Parc automobile comprenant la taille des parcs...,...,0,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",2,2,"{'2024-08': 0, '2024-09': 0, '2024-10': 0, '20...",4396,1475.0,stationnement,stationnement_parc,0.609165

In [56]:
dsdatagouv_mob_class.to_parquet("dsdatagouv_mob_class.parquet")